ChatBot/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.chatbot,name='chatbot' )
]

ToDoListApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.todolist,name='ToDoList' ),
    path('delete/<task_id>',views.delete_task,name='delete_task' ),
    path('edit/<task_id>',views.edit_task,name='edit_task'),
]

ToDoListProject/urls.py
from django.contrib import admin
from django.urls import path,include
from ToDoListApp import views as todolistapp_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',todolistapp_view.index,name='index' ),
    path('account/',include("users_app.urls")),
    path('checklist/',include("CheckListAPP.urls")),
    path('chatbot/',include("ChatBot.urls")),
    path('ToDoList/',include("ToDoListApp.urls")),
    path('office',todolistapp_view.office_work,name='office' ),
    path('physical',todolistapp_view.physical,name='physical' )
]

ToDoListApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ToDoList(models.Model):
    manage = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    task = models.CharField(max_length=300)
    status_type = models.TextChoices("status_type", "TO_DO DEFINED IN_PROGRESS COMPLETED")
    status = models.CharField(blank=True, choices=status_type, max_length=20,default='TO_DO')
    assignee = models.CharField(max_length=300)
    ETA = models.DateField()
    risk_flag = models.BooleanField(default=False)
    
    def __str__(self):
        return self.task 
    
    class Meta:
        ordering = ['id']
    
    

ToDoListApp/forms.py
from django import forms
from ToDoListApp.models import ToDoList

class ToDoListForm(forms.ModelForm):
    class Meta:
        model=ToDoList
        fields=["task","assignee","status","ETA","risk_flag"]

ToDoListApp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from ToDoListApp.models import ToDoList
from ToDoListApp.forms import ToDoListForm
from django.contrib import messages
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

@login_required
def todolist(request):
    if request.method =="POST":
        form = ToDoListForm(request.POST or None)
        if form.is_valid:
            instance=form.save(commit=False)
            instance.manage=request.user
            instance.save()
        messages.success(request,("New Task Added!"))    
        return redirect('ToDoList')
    else:    
        tasks = ToDoList.objects.filter(manage=request.user)
        # tasks = ToDoList.objects.all()
        paginator =Paginator(tasks,5)
        page=request.GET.get('pg')
        tasks=paginator.get_page(page)
        
        context = {'welcome_text':'welcome to to do list',"tasks":tasks}
        return render(request,'ToDoList.html',context)

@login_required    
def delete_task(request,task_id):
    task= ToDoList.objects.get(pk=task_id)
    task.delete()
    return redirect('ToDoList')

@login_required 
def edit_task(request,task_id):
    if request.method =="POST":
        task = ToDoList.objects.get(pk=task_id)
        form = ToDoListForm(request.POST or None , instance=task)
        if form.is_valid:
            form.save()
        messages.success(request,("New Task updated!"))    
        return redirect('ToDoList')
    else:    
        task = ToDoList.objects.get(pk=task_id)
        context = {'welcome_text':'welcome to to do list','task':task}
        return render(request,'edit.html',context)
 
def index(request):
    context = {'welcome_text':'welcome to Task Manager!'}
    return render(request,'index.html',context)    
    
@login_required 
def office_work(request):
    context = {'welcome_text':'welcome to office list'}
    return render(request,'office.html',context)

def physical(request):
    context = {'welcome_text':'welcome to physical list'}
    return render(request,'physical.html',context)

ToDoListApp/templates/ToDoList.html
{% extends "base.html" %}

{% block title %}
<title>ToDoList</title>
{% endblock title %}


{% block  content %}
<div class = 'container'>
    <div class = 'container'>
    <br>
    {% for message in messages%}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    <form method="POST">
      {% csrf_token %}
        <div class="input-group mb-3">
          <span class="input-group-text" id="basic-addon1">Task Name</span>
          <input type="text" class="form-control" placeholder="Task Name"aria-describedby="basic-addon1" name="task">
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1">Assignee</span>
            <input type="text" class="form-control" placeholder="Assignee"aria-describedby="basic-addon1" name="assignee">
        </div>

        <div class="input-group mb-3">
            <span class="input-group-text" id="id_status">Status</span>    
            <select name="status" id="id_status" class="form-control" name ="status">
                <option value="" selected="">---------</option>
                <option value="TO_DO">To do</option>
                <option value="DEFINED">Defined</option>
                <option value="IN_PROGRESS">In Progress</option>
                <option value="COMPLETED">Completed</option>
            </select>
        </div>
          
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1">ETA</span>
            <input type="text" class="form-control" placeholder="YYYY-MM-DD" aria-describedby="basic-addon1" name="ETA">
        </div>
        <div class="input-group mb-3">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" id="defaultCheck1" name="risk_flag">
                <label class="form-check-label" for="defaultCheck1">Risk</label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Add Task</button>
      </form>
    </div>
      <br>
    <table class="table table-bordered">
        <thead class="table-dark">
          <tr>
            <th class="col-3">Task Name</th>
            <th class="col-2">Assignee</th>
            <th class="col-1">Status</th>
            <th class="col-2">ETA</th>
            <th class="col-1">Risk</th>
            <th class="col-1">Edit</th>
            <th class="col-1">Delete</th>
          </tr>
        </thead>
        {% if tasks%}
          <tbody>
            {% for obj in tasks %}
              {% if obj.risk_flag %}
                  <tr class="table-warning">
              {%elif obj.status == 'COMPLETED'%}
                  <tr class="table-success">
              {%else%}
                  <tr>
              {% endif %}
                      <td class="col-5">{{obj.task}}</td>
                      <td class="col-2">{{obj.assignee}}</td>
                      <td class="col-1">{{obj.status}}</td>
                      <td class="col-2">{{obj.ETA}}</td>
                      <td class="col-1">{{obj.risk_flag}}</td>
                      <td class="col-1"><a href="{% url 'edit_task' obj.id %}"><button type="button" class="btn btn-secondary">Edit</button></a></td>
                      <td class="col-1"><a href="{% url 'delete_task' obj.id %}"><button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteConfirmationModal">
                        Delete
                      </button>
                    </a></td>
                  </tr>
            {% endfor %}
          </tbody>
          {% endif %}
        
      </table>
      <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
          <li class="page-item"><a class="page-link" href="?pg=1"><<</a></li>
          {% if tasks.has_previous %}
            <li class="page-item"><a class="page-link" href="?pg={{tasks.previous_page_number}}">{{tasks.previous_page_number}}</a></li>
          {% endif %}
          <li class="page-item"><a class="page-link page-item active">{{tasks.number}}</a></li>
          {% if tasks.has_next %}
            <li class="page-item"><a class="page-link" href="?pg={{tasks.next_page_number}}">{{tasks.next_page_number}}</a></li>
          {% endif %}
          <li class="page-item"><a class="page-link" href="?pg={{tasks.paginator.num_pages}}">>></a></li>
        </ul>
      </nav>
</div>
{% endblock content %}

  

ToDoListApp/templates/edit.html
{% extends "base.html" %}

{% block title %}
<title>Edit task</title>
{% endblock title %}


{% block  content %}
<form method="POST">
    {% csrf_token %}
      <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon1">Task Name</span>
        <input type="text" class="form-control" placeholder="{{task.task}}" value="{{task.task}}" aria-describedby="basic-addon1" name="task">
      </div>
      <div class="input-group mb-3">
          <span class="input-group-text" id="basic-addon1">Assignee</span>
          <input type="text" class="form-control" placeholder={{task.assignee}} value="{{task.assignee}}" aria-describedby="basic-addon1" name="assignee">
      </div>

      <div class="input-group mb-3">
          <span class="input-group-text" id="id_status">Status</span>    
          <select name="status" id="id_status" class="form-control" name ="status" placeholder={{task.status}} value="{{task.status}}">
              <option value="TO_DO">TO_DO</option>
              <option value="DEFINED">DEFINED</option>
              <option value="IN_PROGRESS">IN_PROGRESS</option>
              <option value="COMPLETED">COMPLETED</option>
          </select>
      </div>
        
      <div class="input-group mb-3">
          <span class="input-group-text" id="basic-addon1">ETA</span>
          <input type="text" class="form-control" aria-describedby="basic-addon1" name="ETA" placeholder="YYYY-MM-DD" >
      </div>
      <div class="input-group mb-3">
          <div class="form-check">
              <input class="form-check-input" type="checkbox" id="defaultCheck1" name="risk_flag">
              <label class="form-check-label" for="defaultCheck1">Risk</label>
          </div>
      </div>
      <button type="submit" class="btn btn-primary">Update Task</button>
    </form>
{% endblock content %}

ToDoListApp/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}
<title>Task Manager</title>
{% endblock title %}


{% block  content %}
<div class='container'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body, html {
          margin: 0;
          padding: 0;
          height: 100%;
          overflow: hidden; /* Disable scrolling */
        }
        
        .bg-image {
          background-image: url('background.jpg');
          background-size: cover;
          background-position: center center;
          height: 100%;
          width: 100%;
          position: fixed;
          top: 0;
          left: 0;
          z-index: -1; /* Ensure the background is behind other content */
          filter: blur(0px);
        }
        .overlay {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.5); /* Semi-transparent black overlay */
            z-index: -1; /* Place the overlay behind other content */
          }
        .content {
            text-align: center;
            color: white;
            position: absolute;
            top: 60%;
            left: 50%;
            transform: translate(-50%, -50%);
          }
      </style>
      </head>
      <body>
    <div class="container-fluid p-0">
        <!-- Image as a background -->
        <div class="bg-image" style="background-image: url('{% static 'images/white_1.jpg' %}');"> </div>

        <div class="container">
              <!-- Content on top of the image -->
            <div class="overlay"></div>
            <div class="content">
                <h2>Welcome to Task Manager</h2>
                <h4>Plan Your Day Better</h4>
                <br>
                <a href="{% url 'ToDoList' %}"><button type="submit" class="btn btn-primary shadow">Let's Get Started</button></a>
            </div> 
        </div>
    </div>
      
      
      <!-- Bootstrap JS and dependencies (Optional) -->
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</div>
{% endblock content %}

ToDoListApp/templates/office.html
{% extends "base.html" %}

{% block title %}
<title>Office ToDoList</title>
{% endblock title %}


{% block  content %}
<h1>{{welcome_text}}<h1>
{% endblock content %}

ToDoListApp/templates/physical.html
{% extends "base.html" %}

{% block title %}
<title>Physical ToDoList</title>
{% endblock title %}


{% block  content %}
<h1>{{welcome_text}}<h1>
{% endblock content %}